allow-newer: true
resolver: lts-16.8
compiler: ghc-8.10.7
arch: x86_64
packages:
  - .
extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - th-compat-0.1
  - optics-core-0.3
  - optics-th-0.3
  - optics-extra-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 094ea0d2553c72f38d3704b10ba9157fbace8abe
    subdirs:
      - .
      - liquid-base
      - liquid-prelude
      - liquid-ghc-prim
      - liquid-containers
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 73bf922019259ef6f0581e6bfbec0cee29e5a768
